### ISSUE TITLE
#MindSpore2023 Your Voice Matter — MindSpore Resolution 2023

### ISSUE THREAD

**Issue by lasdjfi** [mindspore-ai/community#6]
Dear valued developers,

MindSpore is our versatile deep learning framework, and we're constantly looking at new ways to make AI modeling and execution more efficient, and as well as cover more scenarios. With 2023 just around the corner, the MindSpore community would like to wish you a happy holiday – we hope you'll give us some feedback, so that we can create a community that best serves your needs.

We'd appreciate it if you could take a few minutes to answer the three questions below – please write your comments on this page. Thank you for your support!

1.	What changes would you like to see to MindSpore in 2023? Feel free to list a few different suggestions.

2.	Are you interested in MindSpore meetups, courses, tutorials, and conferences? If so, which interests you the most? What do you hope to gain from these activities?

3.	Would you consider using MindSpore in your Google Summer of Code (GSoC) projects in 2023? If yes, please give us more details.

The MindSpore community highly values your feedback. We have prepared special Christmas prizes for a few lucky winners. Leave a comment below for the chance to be picked; all winners will be contacted via GitHub. Merry Christmas and a happy new year!

For more info, follow our social media accounts.
Twitter: https://twitter.com/MindSporeOSS
LinkedIn: https://www.linkedin.com/company/80968760/
YouTube: https://www.youtube.com/@MindsporeOSS
Reddit: https://new.reddit.com/r/MindSporeOSS/

**Comment by gomico** [comment]
1. I expect to see MindSpore incorporating more operators of mainstream AI frameworks.
2. I'm most interested in courses about computer vision subfields such as object identification and classification, so that I can try MindSpore on my previous CV projects.
3. I'd be happy to use MindSpore for my planned project of GSoC of a smart camera that can recognize and identify different pets in a house. It's like a face recognition system for animals.
